repos:

# Archivo de configuración de pre-commit

# Configuración de repositorios y ganchos (hooks)
- repo: https://github.com/ambv/black
  rev: 23.12.1
  hooks:
    - id: black
      language_version: python3

- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
    - id: flake8
      args: ["--ignore=E501,E266"]

- repo: https://github.com/PyCQA/bandit
  rev: ''  # Actualiza esto según sea necesario
  hooks:
    - id: bandit
      args:
        - "--skip"
        - "B311"
        - "-x"
        - "test/**"
        - "--skip"
        - "B104"
        - "--skip"
        - "B311"

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.6.1
  hooks:
    - id: mypy
      args: ["--config-file=.code_quality/mypy.ini"]
  additional_dependencies:
    - types-PyMySQL
    - types-requests
    - types-cachetools
    - types-pyyaml
