name: Python CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.5'
        
    - name: Debug directory structure
      run: |
        pwd
        ls -la
        tree
        
    - name: Install tree
      run: sudo apt-get install tree -y
        
    - name: Show project structure
      run: |
        tree
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install --no-interaction
        
    - name: Debug Python path
      run: |
        echo "PYTHONPATH=$PYTHONPATH"
        python -c "import sys; print('\n'.join(sys.path))"
        
    - name: Run tests with debug
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        poetry run python -c "import sys; print(sys.path)"
        poetry run pytest app/test/ --cov=app --cov-report=xml -v --debug
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.xml
        flags: unittests
        fail_ci_if_error: true
        verbose: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
